# Minimal GNOME-style Hyprlock
# For 1366x768 display

# ===== GENERAL =====
general {
    no_fade_in = false
    no_fade_out = false
    grace = 0
    disable_loading_bar = false
    hide_cursor = false
}

animations {
    # Animation for the lock screen fade in/out
    animation = fadeIn, 1, 2, linear
}

# ===== BACKGROUND =====
background {
    monitor =
    path = /home/shashankn120/Downloads/matrixwallpaper.png
    blur_passes = 0
    blur_size = 6
    contrast = 0.9
    brightness = 0.75
    vibrancy = 0.15
}
# ===== TIME - HOUR =====
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I")</span>"
    color = rgba(225, 153, 248, 1) 
    font_size = 100
    font_family = StretchPro
    position = -500, 190
    halign = center
    valign = center
}

# ===== TIME - MINUTE =====
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%M")</span>"
    color = rgba(225, 153, 248, 1)
    font_size = 100
    font_family = StretchPro
    position = -400, 100
    halign = center
    valign = center
}

# ===== DATE =====
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%d %B, %A")"
    color = rgba(247, 224, 255, 1)
    font_size = 16
    font_family = StretchPro
    position = -450, 20
    halign = center
    valign = center
}

# ===== PROFILE IMAGE =====
image {
    monitor =
    path = /home/shashankn120/Pictures/Screenshots/pfp1
    size = 150
    rounding = -1
    border_size = 0
    border_color = rgba(134, 31, 166, 1)
    position = -450, -120
    halign = center
    valign = center
}

# ===== USERNAME =====
label {
    monitor =
    text = $USER
    color = rgba(247, 224, 255, 1)
    font_size = 16
    font_family = StretchPro
    position = -450, -230
    halign = center
    valign = center
}

# ===== PASSWORD INPUT =====
input-field {
    monitor =
    size = 250, 45
    outline_thickness = 0
    dots_size = 0.25
    dots_spacing = 0.25
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(225, 153, 248, 1)
    font_color = rgba(255, 255, 255, 0.9)
    fade_on_empty = false
    font_family = StretchPro
    placeholder_text = <span foreground="##ffffff99">password</span>
    hide_input = false
    rounding = 22
    position = -450, -280
    halign = center
    valign = center
}
